CREATE TABLE account (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL CHECK (length(username) >= 4 AND length(username) <= 32 AND username NOT LIKE '% %') UNIQUE,
    token_version integer NOT NULL DEFAULT 1,
    password_hash text NOT NULL CHECK (length(password_hash) >= 8 AND length(password_hash) <= 40), 
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    updated_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE TABLE note (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    title text NOT NULL CHECK (length(trim(title)) > 0 AND length(title) < 40),
    parent_id BIGINT,
    icon_emoji TEXT CHECK (icon_emoji IS NULL OR length(icon_emoji) <= 10),
    cover_picture_url TEXT CHECK (cover_picture_url IS NULL OR length(cover_picture_url) <= 500),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    updated_at timestamptz NOT NULL DEFAULT current_timestamp,

    CONSTRAINT user_id_fk FOREIGN KEY (user_id)
        REFERENCES account (id) ON DELETE CASCADE,
    CONSTRAINT note_parent_id_fkey FOREIGN KEY (parent_id)
        REFERENCES note (id) ON DELETE CASCADE,
    CONSTRAINT note_user_title_parent_unique UNIQUE (user_id, title, parent_id),
    CONSTRAINT note_no_self_parent CHECK (id != parent_id)
);

CREATE TABLE block_type (
    id smallint PRIMARY KEY CHECK (id > 0),
    name text NOT NULL CHECK (length(name) > 0 AND length(name) <= 50) UNIQUE
);

CREATE TABLE attachment (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL CHECK (length(file_name) > 0 AND length(file_name) <= 255),
    file_size BIGINT NOT NULL CHECK (file_size > 0),
    mime_type TEXT NOT NULL CHECK (length(mime_type) > 0 AND length(mime_type) <= 100),
    storage_url TEXT NOT NULL CHECK (length(storage_url) > 0 AND length(storage_url) <= 1000) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp
);

CREATE TABLE block (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_id BIGINT NOT NULL REFERENCES note(id) ON DELETE CASCADE,
    position integer NOT NULL CHECK (position >= 0),
    block_type_id SMALLINT NOT NULL REFERENCES block_type(id) ON DELETE RESTRICT,
    content text,
    attachment_id BIGINT REFERENCES attachment(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    updated_at timestamptz NOT NULL DEFAULT current_timestamp,

    CONSTRAINT block_note_position_unique UNIQUE (note_id, position)
);

CREATE TABLE block_state (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    block_id BIGINT NOT NULL REFERENCES block(id) ON DELETE CASCADE,
    formatting text NOT NULL CHECK (length(formatting) > 0),
    created_at timestamptz NOT NULL DEFAULT current_timestamp,
    updated_at timestamptz NOT NULL DEFAULT current_timestamp
);

CREATE TABLE note_share (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_id BIGINT NOT NULL REFERENCES note(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    permission TEXT NOT NULL CHECK (permission IN ('R', 'W')),
    shared_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    shared_by_user_id BIGINT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    
    CONSTRAINT note_share_unique UNIQUE (note_id, user_id)
);

CREATE TABLE favorite_note (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    note_id BIGINT NOT NULL REFERENCES note(id) ON DELETE CASCADE,
    added_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    
    CONSTRAINT favorite_note_unique UNIQUE (user_id, note_id)
);

CREATE TABLE note_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_id BIGINT NOT NULL REFERENCES note(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    icon_emoji TEXT,
    cover_picture_url TEXT,
    parent_id BIGINT,
    operation TEXT NOT NULL CHECK (operation IN ('UPDATE', 'DELETE')),
    changed_at TIMESTAMPTZ NOT NULL DEFAULT current_timestamp,
    changed_by_user_id BIGINT NOT NULL REFERENCES account(id) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION set_timestamps_current_time()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.created_at = CURRENT_TIMESTAMP;
        NEW.updated_at = CURRENT_TIMESTAMP;
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.updated_at = CURRENT_TIMESTAMP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_account_timestamps 
    BEFORE INSERT OR UPDATE ON account
    FOR EACH ROW 
    EXECUTE FUNCTION set_timestamps_current_time();

CREATE TRIGGER set_note_timestamps 
    BEFORE INSERT OR UPDATE ON note
    FOR EACH ROW 
    EXECUTE FUNCTION set_timestamps_current_time();

CREATE TRIGGER set_block_timestamps 
    BEFORE INSERT OR UPDATE ON block
    FOR EACH ROW 
    EXECUTE FUNCTION set_timestamps_current_time();

CREATE TRIGGER set_block_timestamps 
    BEFORE INSERT OR UPDATE ON block_state
    FOR EACH ROW 
    EXECUTE FUNCTION set_timestamps_current_time();

CREATE OR REPLACE FUNCTION note_history_trigger()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.is_deleted = FALSE AND 
       (OLD.title != NEW.title OR OLD.icon_emoji IS DISTINCT FROM NEW.icon_emoji OR 
        OLD.cover_picture_url IS DISTINCT FROM NEW.cover_picture_url OR OLD.parent_id IS DISTINCT FROM NEW.parent_id) THEN
        INSERT INTO note_history (note_id, title, icon_emoji, cover_picture_url, parent_id, operation, changed_by_user_id)
        VALUES (OLD.id, OLD.title, OLD.icon_emoji, OLD.cover_picture_url, OLD.parent_id, 'UPDATE', NEW.user_id);
    ELSIF TG_OP = 'DELETE' AND OLD.is_deleted = FALSE THEN
        INSERT INTO note_history (note_id, title, icon_emoji, cover_picture_url, parent_id, operation, changed_by_user_id)
        VALUES (OLD.id, OLD.title, OLD.icon_emoji, OLD.cover_picture_url, OLD.parent_id, 'DELETE', OLD.user_id);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER note_history_trigger
    AFTER UPDATE OR DELETE ON note
    FOR EACH ROW
    EXECUTE FUNCTION note_history_trigger();
